# Site settings
title: Ordina VisionWorks Tech Blog
email: datatalks@ordina.be
description: > # this means to ignore newlines until "baseurl:"
  Insert Description here
metadata:
    author: Ordina Belgium
    keywords: Ordina,VisionWorks
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ordina-visionworks.github.io" # the base hostname & protocol for your site
twitter_username: lifeatordinabe
github_username:  ordina-visionworks
facebook: lifeatordinabe
gems: [jekyll-paginate, jekyll-feed]
# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

# Pagination
paginate: 10

collections:
    # Needed for our job board
    jobs:
        output: true
        permalink: /jobs/:path/

defaults:
  - scope:
      path: ""
      type: jobs
    values:
      layout: job
